---
title: "Lesson Plan"
description: |
  Some additional details about the website
author: 
  - name: "Kamarul Ariffin Mansor"
    url: https://my.linkedin.com/in/kamarul-ariffin-mansor-254b9ba7/
    affiliation: Universiti Teknologi MARA
    affiliation_url: https://kedah.uitm.edu.my/v2/index.php
date: 10-13-2021
output: 
  distill::distill_article:
    self_contained: true
    toc: true
    toc_float: true
    toc_level: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(slickR)
```

## Weekly Scheme of Work  

### Session 20214  

```{r}
slickR::slickR(
    list.files("./images/sow/",full.names = TRUE,pattern = 'jpg'),
    height = 700,
    width = '95%')
```  

<aside>
[Download - Scheme of Work](./files/Scheme of Work STA404_TP_Oct 2021-Jan 2022_Terkini.pdf)
</aside>

***  

## Presentations Slides  

### Chapter 1  

```{r}
slickR::slickR(
    list.files("./files/slides/Unit 1 Introduction to Statistics/",full.names = TRUE,pattern = 'jpg'),
    height = 400,
    width = '95%')
```  

<aside>
[Download - Unit 1 Introduction to Statistics](./files/slides/Unit 1 Introduction to Statistics.pdf)
</aside>

***  

### Chapter 2  

Under constructions  

***  

### Chapter 3 - Estimations  

#### Confidence Interval Estimation  

```{r}
slickR::slickR(
    list.files("./files/slides/Unit 3 Estimation 1/",full.names = TRUE,pattern = 'jpg'),
    height = 400,
    width = '95%')
```  

<aside>
[Download - Unit 3 - Estimations - Confidence Interval Estimation](./files/slides/Unit 3 - Estimations - Confidence Interval Estimation.pdf)
</aside>

***  

#### Sampling Distributions  

```{r}
slickR::slickR(
    list.files("./files/slides/Unit 3 Estimation 2/",full.names = TRUE,pattern = 'jpg'),
    height = 400,
    width = '95%')
```

<aside>
[Download - Unit 3 - Estimations - Sampling Distributions](./files/slides/Unit 3 - Estimations - Sampling Distributions.pdf)
</aside>

***  

### Chapter 4 - Hypothesis Testing  

#### Difference Between Two Means  

```{r}
slickR::slickR(
    list.files("./files/slides/Chapter 4 Hypothesis Testing 2/",full.names = TRUE,pattern = 'jpg'),
    height = 400,
    width = '95%')
```

<aside>
[Download - Chapter 4 HYPOTHESIS TESTING 2](./files/slides/Chapter 4 HYPOTHESIS TESTING 2.pdf)
</aside>

***  

#### Difference Between Two Means (Paired Sample)  

```{r}
slickR::slickR(
    list.files("./files/slides/Chapter 4 Hypothesis Testing 3/",full.names = TRUE,pattern = 'jpg'),
    height = 400,
    width = '95%')
```  

<aside>
[Download - Chapter 4 HYPOTHESIS TESTING 3](./files/slides/Chapter 4 HYPOTHESIS TESTING 3.pdf)
</aside>

***

#### One-Way Analysis of Variance (ANOVA)  

```{r}
slickR::slickR(
    list.files("./files/slides/Chapter 4 ANOVA/",full.names = TRUE,pattern = 'jpg'),
    height = 400,
    width = '95%')
```

<aside>
[Download - Chapter 4 ANOVA](./files/slides/Chapter 4 ANOVA.pdf)
</aside>

***  

### Chapter 5  

Under constructions  

***